// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package database

import (
	"context"
	"database/sql"
)

const getAttendanceByStudentID = `-- name: GetAttendanceByStudentID :many
SELECT 
    students.name AS name,
    students.email AS email,
    attendance.status AS status,
    attendance.date AS date
FROM attendance 
JOIN students
ON students.id = attendance.student_id
WHERE attendance.student_id = ?
`

type GetAttendanceByStudentIDRow struct {
	Name   string           `json:"name"`
	Email  string           `json:"email"`
	Status AttendanceStatus `json:"status"`
	Date   sql.NullTime     `json:"date"`
}

func (q *Queries) GetAttendanceByStudentID(ctx context.Context, studentID string) ([]GetAttendanceByStudentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceByStudentIDRow
	for rows.Next() {
		var i GetAttendanceByStudentIDRow
		if err := rows.Scan(
			&i.Name,
			&i.Email,
			&i.Status,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceSummary = `-- name: GetAttendanceSummary :one
SELECT
    SUM(CASE WHEN status = 'PRESENT' THEN 1 ELSE 0 END) AS present_days,
    COUNT(*) AS total_days
FROM attendance
WHERE student_id = ?
`

type GetAttendanceSummaryRow struct {
	PresentDays interface{} `json:"present_days"`
	TotalDays   int64       `json:"total_days"`
}

func (q *Queries) GetAttendanceSummary(ctx context.Context, studentID string) (GetAttendanceSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getAttendanceSummary, studentID)
	var i GetAttendanceSummaryRow
	err := row.Scan(&i.PresentDays, &i.TotalDays)
	return i, err
}

const markAttendance = `-- name: MarkAttendance :exec
INSERT INTO attendance(student_id, status)
VALUES (
    ?,
    ?
)
`

type MarkAttendanceParams struct {
	StudentID string           `json:"student_id"`
	Status    AttendanceStatus `json:"status"`
}

func (q *Queries) MarkAttendance(ctx context.Context, arg MarkAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, markAttendance, arg.StudentID, arg.Status)
	return err
}
