// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package database

import (
	"context"
	"database/sql"
)

const getAttendanceByStudentID = `-- name: GetAttendanceByStudentID :many
SELECT 
    students.name AS name,
    students.email AS email,
    attendance.status AS status,
    attendance.date AS date
FROM attendance 
JOIN students
ON students.id = attendance.student_id
WHERE attendance.student_id = ?
`

type GetAttendanceByStudentIDRow struct {
	Name   string           `json:"name"`
	Email  string           `json:"email"`
	Status AttendanceStatus `json:"status"`
	Date   sql.NullTime     `json:"date"`
}

func (q *Queries) GetAttendanceByStudentID(ctx context.Context, studentID string) ([]GetAttendanceByStudentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceByStudentIDRow
	for rows.Next() {
		var i GetAttendanceByStudentIDRow
		if err := rows.Scan(
			&i.Name,
			&i.Email,
			&i.Status,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyAttendanceSummary = `-- name: GetMonthlyAttendanceSummary :many
SELECT
    a.student_id AS student_id,
    s.name AS name,
    s.email AS email,
    CAST(SUM(CASE WHEN a.status = 'PRESENT' THEN 1 ELSE 0 END) AS UNSIGNED) AS present_days,
    COUNT(*) AS total_days
FROM attendance a
JOIN students s 
ON s.id = a.student_id
WHERE a.date >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH), '%Y-%m-01')
AND a.date <  DATE_FORMAT(CURDATE(), '%Y-%m-01')
GROUP BY a.student_id, s.name, s.email
`

type GetMonthlyAttendanceSummaryRow struct {
	StudentID   string `json:"student_id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	PresentDays int64  `json:"present_days"`
	TotalDays   int64  `json:"total_days"`
}

func (q *Queries) GetMonthlyAttendanceSummary(ctx context.Context) ([]GetMonthlyAttendanceSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyAttendanceSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyAttendanceSummaryRow
	for rows.Next() {
		var i GetMonthlyAttendanceSummaryRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Name,
			&i.Email,
			&i.PresentDays,
			&i.TotalDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyAttendanceSummary = `-- name: GetWeeklyAttendanceSummary :many
SELECT
    a.student_id AS student_id,
    s.name AS name,
    s.email AS email,
    CAST(SUM(CASE WHEN a.status = 'PRESENT' THEN 1 ELSE 0 END) AS UNSIGNED) AS present_days,
    COUNT(*) AS total_days
FROM attendance a
JOIN students s 
ON s.id = a.student_id
WHERE a.date >= DATE_SUB(CURDATE(), INTERVAL 6 DAY)
AND a.date <= CURDATE()
GROUP BY a.student_id, s.name, s.email
`

type GetWeeklyAttendanceSummaryRow struct {
	StudentID   string `json:"student_id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	PresentDays int64  `json:"present_days"`
	TotalDays   int64  `json:"total_days"`
}

func (q *Queries) GetWeeklyAttendanceSummary(ctx context.Context) ([]GetWeeklyAttendanceSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeeklyAttendanceSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeeklyAttendanceSummaryRow
	for rows.Next() {
		var i GetWeeklyAttendanceSummaryRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Name,
			&i.Email,
			&i.PresentDays,
			&i.TotalDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttendance = `-- name: MarkAttendance :exec
INSERT INTO attendance(student_id, status)
VALUES (
    ?,
    ?
)
`

type MarkAttendanceParams struct {
	StudentID string           `json:"student_id"`
	Status    AttendanceStatus `json:"status"`
}

func (q *Queries) MarkAttendance(ctx context.Context, arg MarkAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, markAttendance, arg.StudentID, arg.Status)
	return err
}
