// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AttendanceStatus string

const (
	AttendanceStatusPRESENT AttendanceStatus = "PRESENT"
	AttendanceStatusABSENT  AttendanceStatus = "ABSENT"
)

func (e *AttendanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendanceStatus(s)
	case string:
		*e = AttendanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendanceStatus: %T", src)
	}
	return nil
}

type NullAttendanceStatus struct {
	AttendanceStatus AttendanceStatus `json:"attendance_status"`
	Valid            bool             `json:"valid"` // Valid is true if AttendanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttendanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendanceStatus), nil
}

type Attendance struct {
	ID        string           `json:"id"`
	StudentID string           `json:"student_id"`
	Date      sql.NullTime     `json:"date"`
	Status    AttendanceStatus `json:"status"`
}

type Student struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	Department string    `json:"department"`
	CreatedAt  time.Time `json:"created_at"`
}
