// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package database

import (
	"context"
)

const createStudent = `-- name: CreateStudent :exec
INSERT INTO students(email, name, department)
VALUES (
    ?,
    ?,
    ?
)
`

type CreateStudentParams struct {
	Email      string `json:"email"`
	Name       string `json:"name"`
	Department string `json:"department"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent, arg.Email, arg.Name, arg.Department)
	return err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students WHERE id = ?
`

func (q *Queries) DeleteStudent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, id)
	return err
}

const getAllStudents = `-- name: GetAllStudents :many
SELECT id, name, email, department, created_at FROM students
`

func (q *Queries) GetAllStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, getAllStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Department,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT id, name, email, department, created_at FROM students
WHERE email = ?
`

func (q *Queries) GetStudentByEmail(ctx context.Context, email string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByEmail, email)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, name, email, department, created_at FROM students
WHERE id = ?
`

func (q *Queries) GetStudentByID(ctx context.Context, id string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.CreatedAt,
	)
	return i, err
}

const updateStudent = `-- name: UpdateStudent :exec
UPDATE students
SET 
    name = ?,
    department = ?
WHERE id = ?
`

type UpdateStudentParams struct {
	Name       string `json:"name"`
	Department string `json:"department"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) error {
	_, err := q.db.ExecContext(ctx, updateStudent, arg.Name, arg.Department, arg.ID)
	return err
}
