services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: hrms
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - stonks_mysql:/var/lib/mysql

volumes:
  stonks_mysql:
